/* eslint-disable max-len */
import { IRecord } from "@neutrino/core";

const DATA: IRecord[] = [
  {
      parentId: "navigation",
      metadata: {},
      deletedAt: null,
      updatedAt: 1653117684216,
      order: 0,
      id: "index",
      slug: "index",
      templateId: "index-page",
      createdAt: 1653117684216,
      name: "Home",
      content: {
          cta_3: {
              description: null,
              name: "Contribute",
              favicon: null,
              recordId: null,
              keywords: [],
              title: null,
              url: "Testing",
          },
          endorsements_title: "   ",
          cta_1: {
              url: null,
              description: null,
              keywords: [],
              name: "Campaign Store",
              favicon: null,
              recordId: "fjtn89swt4",
              title: null,
          },
          cta_2: {
              recordId: "663o525ymt",
              name: "Take Action",
              favicon: null,
              keywords: [],
              url: null,
              title: null,
              description: null,
          },
          "endorsements-collection": {
              collectionId: "e9uhubnabe",
              sort: null,
              order: "desc",
              limit: null,
          },
          show_issues: [
              "show_issues",
          ],
          volunteer_image: {
              src: "uploads/ab52ad12bf070c4b8a068efe5405e026",
              focus: {
                  y: 0.23794014084507042,
                  x: -0.29348859112119524,
              },
          },
          issues__description: "<h3>On the Issues</h3>",
          show_about: [
              "show_about",
          ],
          about_body: "<h3><span style=\"color: var(--cta-5);\">ABOUT</span></h3><h1><span class=\"ql-font-serif\">The Candidate</span></h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor. Voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p><br></p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore.</p><p><br></p><a class=\"quill-button\" id=\"2c4884a5-3853-4993-ac35-efafddc05cf2\" contenteditable=\"false\" tabindex=\"-1\" data-format=\"right\" href=\"/about\"><span class=\"quill-button__text\">Learn More</span></a>",
          endorsements__description: "<h2>Endorsements</h2><p>We're proud to have the support of many amazing community members</p>",
          show_volunteer: [
              "show_volunteer",
          ],
          about_image: {
              src: "uploads/ae89c49a7c788b63b67fe2daa15a11ba",
              focus: {
                  x: 0,
                  y: 0,
              },
          },
          subtitle: "Take Action",
          volunteer_header: "Take Action",
          header_image: {
              src: "uploads/639354eb28e9678d7f9592b09cdee221",
              focus: {
                  x: 0,
                  y: 0,
              },
          },
          endorsements: {
              sort: null,
              order: "desc",
              limit: null,
              collectionId: "e9uhubnabe",
          },
          about_title: "About",
          title: "Building a better community by working together.",
          endorsements_cta: {
              url: null,
              description: null,
              keywords: null,
              recordId: "e9uhubnabe",
              name: "See All Endorsements",
              favicon: null,
              title: null,
          },
          issues: {
              sort: null,
              order: "desc",
              collectionId: "yyjpkpjujo",
              limit: null,
          },
          show_endorsements: [
              "show_endorsements",
          ],
          issues_cta: {
              name: "See All Issues",
              url: null,
              title: null,
              recordId: "yyjpkpjujo",
              keywords: null,
              description: null,
              favicon: null,
          },
      },
  },
  {
      updatedAt: 1659602871095,
      name: "About",
      metadata: {},
      order: 1,
      parentId: "navigation",
      id: "1qjan406ox",
      content: {
          title: "About Universe",
          header_image: {
              blurhash: "LPFYGm~U9D9H~p-pIVRiSbohakn}",
              focus: {
                  x: 0,
                  y: 0,
              },
              width: 1,
              type: "gif",
              src: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",
              height: 1,
              aspectRatio: 1,
          },
          subtitle: "Campaign Tech for Everyone",
          body: "<p class=\"ql-align-justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vulputate tincidunt elit, non molestie elit convallis nec. Aenean vel justo purus. Curabitur sodales tempus accumsan. Vivamus molestie, velit ut efficitur posuere, augue quam tincidunt leo, ultrices dignissim erat nibh sit amet urna. Sed elementum maximus accumsan. Nulla ut lorem sem. Proin malesuada lacus a ipsum luctus, ac hendrerit quam condimentum. Cras orci enim, viverra vitae libero sollicitudin, pharetra interdum lorem. Sed placerat dignissim elit, eget tristique dolor semper et. Pellentesque mollis ultricies augue eu ornare. Pellentesque ultricies rhoncus mi, eu eleifend velit porta id.</p><p class=\"ql-align-justify\">Sed cursus lorem id faucibus placerat. Ut pharetra dapibus purus at sagittis. Fusce ut metus pulvinar, aliquam nunc ac, fringilla elit. Sed quam tellus, bibendum in nisl a, iaculis placerat dolor. Sed pulvinar posuere turpis, et interdum velit convallis dignissim. Nam ornare diam eget massa sodales, in maximus tellus commodo. Suspendisse ultrices, ante et cursus placerat, ipsum urna consectetur neque, ac congue ex neque vel neque. Pellentesque mattis pretium libero. Quisque fringilla est turpis, molestie vehicula arcu bibendum sed. Mauris nec ullamcorper lacus, at eleifend quam. Etiam vel finibus nibh.</p><blockquote class=\"ql-align-justify\">Proin finibus nibh erat, eget mollis odio finibus non. Nullam placerat felis posuere justo ultrices, vehicula vestibulum eros sodales.</blockquote><p class=\"ql-align-justify\">Proin non quam lobortis, dapibus erat ut, aliquam dolor. Etiam id faucibus est, sit amet faucibus augue. Praesent ornare erat sit amet tincidunt rutrum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis dictum fringilla lectus id sollicitudin. Morbi imperdiet placerat fringilla. Aliquam sit amet tincidunt arcu. Aenean efficitur condimentum risus dignissim feugiat. Integer vel sapien quis elit cursus porta. Nullam posuere bibendum maximus. Etiam finibus dolor metus, in tempus urna bibendum ut. Aenean dapibus elit pharetra elit suscipit, placerat molestie turpis lacinia. Phasellus porta efficitur rutrum. Aenean in lobortis ligula. Duis eget purus vel metus pellentesque blandit. Vestibulum commodo porta massa, id blandit felis ornare quis.</p><p class=\"ql-align-justify\">Sed cursus viverra congue. Morbi non blandit velit. Suspendisse vestibulum, turpis eget tristique placerat, mi purus fermentum quam, ac sagittis neque elit non eros. Aliquam mauris massa, bibendum ut nulla eget, faucibus posuere sapien. Aliquam maximus ut urna sed rhoncus. Aliquam eu erat ut risus porttitor rhoncus sit amet in felis. Suspendisse id volutpat lacus, a venenatis felis. Vestibulum eget quam ligula. Duis faucibus vel metus sed dictum. Praesent vel purus nisl. Praesent tortor elit, feugiat vel fringilla nec, facilisis a nisl. Nunc auctor, risus non porta congue, metus purus volutpat ligula, in viverra tortor nisi a sapien. Vestibulum ornare ut erat id egestas. Sed consectetur sit amet lacus eget condimentum. Proin finibus nibh erat, eget mollis odio finibus non. Nullam placerat felis posuere justo ultrices, vehicula vestibulum eros sodales.</p><p class=\"ql-align-justify\">Nulla ullamcorper, tortor sit amet consequat eleifend, urna neque faucibus tellus, consequat tempor enim massa quis tortor. Morbi fringilla dui vestibulum, iaculis odio vel, vehicula ipsum. Aenean in tristique nulla. Nam tincidunt nunc quis quam rutrum, non facilisis nibh vulputate. Phasellus sit amet vehicula justo, vitae aliquet tortor. Curabitur eget dapibus quam. Quisque vel ultrices velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi ullamcorper, ante id tincidunt cursus, lorem turpis interdum turpis, eget facilisis nulla turpis vel elit. Aliquam feugiat enim vel sapien egestas, quis finibus magna accumsan.</p><p><br></p>",
      },
      deletedAt: null,
      createdAt: 1659602871095,
      slug: "about",
      templateId: "page-page",
  },
  {
      parentId: "navigation",
      name: "Issues",
      order: 2,
      templateId: "issues-page",
      createdAt: 1656103259219,
      updatedAt: 1656103259219,
      content: {
          header_text: "",
          subtitle: "",
          issues: {
              collectionId: "yyjpkpjujo",
              limit: null,
              order: "desc",
              sort: null,
          },
          title: "On the Issues",
      },
      slug: "issues",
      id: "yyjpkpjujo",
      metadata: {},
      deletedAt: null,
  },
  {
      slug: "endorsements",
      name: "Endorsements",
      deletedAt: null,
      updatedAt: 1653117748606,
      id: "e9uhubnabe",
      content: {
          header_text: "<p><br></p><a class=\"quill-button\" id=\"4a0dc5af-132a-4391-8524-1cdfa9b04460\" contenteditable=\"false\" tabindex=\"-1\" data-format=\"left\" href=\"#\"><span class=\"quill-button__text\">Add Your Endorsement</span></a><p><br></p>",
          endorsements: {
              order: "desc",
              collectionId: "e9uhubnabe",
              sort: null,
              limit: null,
          },
          title: "Endorsements",
          header_image: {
              src: "uploads/ab52ad12bf070c4b8a068efe5405e026",
          },
          subtitle: "We're proud to have the support of many amazing community members.",
          "endorsements-collection": {
              sort: null,
              limit: null,
              collectionId: "e9uhubnabe",
              order: "desc",
          },
      },
      order: 3,
      metadata: {},
      templateId: "endorsements-page",
      createdAt: 1653117748606,
      parentId: "navigation",
  },
  {
      name: "News",
      id: "ppbq9qdylv",
      order: 4,
      parentId: "navigation",
      updatedAt: 1658654130166,
      metadata: {},
      templateId: "news-page",
      deletedAt: null,
      createdAt: 1658654130166,
      slug: "news",
      content: {
          "news-collection": {
              order: "desc",
              collectionId: "ppbq9qdylv",
              sort: null,
              limit: null,
          },
          title: "Campaign Updates",
          news: {
              sort: null,
              order: "desc",
              collectionId: "ppbq9qdylv",
              limit: null,
          },
      },
  },
  {
      order: null,
      createdAt: 1658444960957,
      parentId: "dbyt9fksrv",
      metadata: {},
      updatedAt: 1658444960957,
      id: "zwwi650981",
      content: {
          for_identification_only: [
              "for_identification_only",
          ],
          type: [
              "labor",
          ],
          name: "Testing Second Endorsements",
          title: "Woo",
      },
      deletedAt: null,
      name: "Test Second Endorsement",
      templateId: "endorsements-collection",
      slug: "endorsement--zwwi650981",
  },
  {
      deletedAt: null,
      templateId: "endorsements-collection",
      metadata: {},
      order: null,
      content: {
          for_identification_only: [
              "for_identification_only",
          ],
          title: "Awesome",
          name: "New Person",
          type: [
              "elected_officials",
          ],
      },
      id: "xkfc35s5sb",
      slug: "endorsement--xkfc35s5sb",
      updatedAt: 1661339674301,
      createdAt: 1661339674301,
      parentId: "e9uhubnabe",
      name: null,
  },
  {
      deletedAt: null,
      createdAt: 1658668634486,
      id: "u9z5dxn4om",
      slug: "endorsement--u9z5dxn4om",
      metadata: {},
      updatedAt: 1658668634486,
      templateId: "endorsements-collection",
      name: null,
      parentId: "e9uhubnabe",
      order: null,
      content: {
          image: {
              focus: {
                  x: 0,
                  y: 0,
              },
              src: "uploads/ed9351437b0c00a9f8b2c91eb0d84df7",
          },
          name: "Erica Oh",
          type: [
              "team",
          ],
          title: "Software Engineer",
      },
  },
  {
      name: null,
      content: {
          type: [
              "team",
          ],
          name: "Adam Miller",
          image: {
              src: "uploads/8826657a7bc577445a2603df2b83f23a",
          },
          title: "Founder / CEO",
      },
      slug: "endorsement--ope1spxmmo",
      parentId: "e9uhubnabe",
      templateId: "endorsements-collection",
      deletedAt: null,
      updatedAt: 1653117773146,
      id: "ope1spxmmo",
      createdAt: 1653117773146,
      order: null,
      metadata: {},
  },
  {
      order: null,
      deletedAt: null,
      updatedAt: 1659601357420,
      parentId: "3ei9a69juc",
      metadata: {},
      id: "l0n589tt1n",
      name: null,
      templateId: "petitions-collection",
      createdAt: 1659601357420,
      slug: "petition--l0n589tt1n",
      content: {
          body: "<p><em style=\"color: rgb(54, 49, 53);\">This morning,</em><strong style=\"color: rgb(54, 49, 53);\"><em>&nbsp;the Supreme Court officially overturned Roe v. Wade</em></strong><em style=\"color: rgb(54, 49, 53);\">, despite the fact that 61% of Americans support the right to safe abortion. A majority of our Senators and Representatives –&nbsp;even some moderate Republicans – say they believe in keeping abortion legal and safe. It’s time for them to live up to their word.&nbsp;</em><strong style=\"color: rgb(54, 49, 53);\"><em>Congress must act NOW and agree on legislation that offers federal protection for access to abortion – regardless of where a pregnant person lives.</em></strong></p>",
          enable_name: [
              "enable_name",
          ],
          enable_phone: [
              "enable_phone",
          ],
          enable__zip: [
              "enable_zip",
          ],
          image: {
              src: "uploads/e0167174b1dbd10aa0e16d1af5b69969",
          },
          title: "Congress: Protect our Right to Choose!",
      },
  },
  {
      id: "ivlmjuxkw3",
      content: {
          name: "Jenny Silber",
          image: {
              src: "uploads/293683340426bf79307965d36ed3c6aa",
          },
          type: [
              "team",
          ],
          title: "Growth & Partnerships",
      },
      createdAt: 1653118485330,
      deletedAt: null,
      name: null,
      templateId: "endorsements-collection",
      updatedAt: 1653118485330,
      slug: "endorsement--ivlmjuxkw3",
      parentId: "e9uhubnabe",
      order: null,
      metadata: {},
  },
  {
      name: "Store",
      createdAt: 1659664603104,
      templateId: "store-page",
      parentId: null,
      slug: "store",
      order: null,
      updatedAt: 1659664603104,
      metadata: {},
      id: "fjtn89swt4",
      deletedAt: null,
      content: {
          title: "Campaign Store",
          subtitle: "Show your support with Universe branded schwag!",
          goodstockSubdomain: "universe",
          header_text: "",
      },
  },{
    parentId: null,
    metadata: {},
    deletedAt: null,
    updatedAt: Date.now(),
    order: 0,
    id: "callstoaction-settings",
    slug: "callstoaction-settings",
    templateId: "callstoaction-settings",
    createdAt: Date.now(),
    name: null,
    content: {
        cta_1: {
            url: "/",
            description: null,
            keywords: [],
            name: "Campaign Store",
            favicon: null,
            recordId: null,
            title: null,
        },
        cta_2: {
            recordId: null,
            name: "Take Action",
            favicon: null,
            keywords: [],
            url: "/",
            title: null,
            description: null,
        },
        cta_3: {
            description: null,
            name: "Contribute",
            favicon: null,
            recordId: null,
            keywords: [],
            title: null,
            url: "/",
        },
    },
  }, {
      metadata: {},
      content: {
          header_image: {
              src: "uploads/fdea8ffec6b0e8d019bb028693cd8960",
              focus: {
                  x: 0,
                  y: 0,
              },
          },
          title: "Policy Update",
          collection: [
              "policy",
          ],
          body: "<p class=\"ql-align-justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent congue mauris orci, sit amet dictum nulla interdum suscipit. Praesent efficitur fermentum quam quis ornare. Curabitur ut eleifend mi. Donec hendrerit consequat lacus, ac sollicitudin augue venenatis non. Fusce nec augue tincidunt, mattis dui nec, tincidunt leo. Donec non urna sollicitudin, aliquet orci ut, tincidunt elit. Phasellus est felis, pulvinar vitae commodo non, vulputate eget nibh. Ut at ante ut risus tempor posuere. In justo metus, condimentum vel eleifend hendrerit, scelerisque et quam. Suspendisse dignissim condimentum arcu quis vehicula. Quisque suscipit tristique ex eget pulvinar. Pellentesque quis laoreet augue, eu efficitur urna. Praesent ullamcorper arcu mattis ornare cursus.</p><p class=\"ql-align-justify\">Nunc non ornare eros. Nullam quis libero dictum mi posuere tempor. Vivamus vestibulum ullamcorper orci, eu aliquam lacus varius ac. Suspendisse in dictum nibh. Nam posuere pharetra lorem, eu tincidunt augue bibendum non. Nullam vulputate felis orci, ac ullamcorper nibh dignissim at. Proin a augue eu nisi pulvinar malesuada sed at diam.</p><p class=\"ql-align-justify\">Vivamus fermentum ullamcorper enim, ut sodales ligula dignissim sed. Proin vel lobortis neque. Cras consectetur tempus lacus ut fringilla. Fusce vitae augue et felis sodales blandit. Integer a quam justo. Vestibulum arcu ipsum, facilisis vel magna sit amet, egestas ultrices quam. Donec id gravida lectus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse dictum sem at quam lacinia consequat.</p><p class=\"ql-align-justify\">Maecenas vitae lobortis orci. Integer ac sem sodales, aliquam dui in, cursus nunc. Donec feugiat arcu libero, sit amet pretium risus efficitur vitae. Quisque commodo, velit et malesuada volutpat, justo lectus blandit risus, eget suscipit lorem magna sit amet enim. Duis lobortis fermentum venenatis. Sed vel libero sed enim tincidunt mollis. Donec cursus orci vel risus ultrices efficitur. Pellentesque venenatis sed leo a ullamcorper. Cras id lacus ex. Etiam quis commodo erat. Aenean magna ipsum, sodales a elementum sed, fringilla at ligula. Fusce tincidunt iaculis erat, eu tempus erat fermentum sed. Cras at ex mollis, tristique ante a, mollis libero. Suspendisse tempor varius diam a efficitur. Aenean at ullamcorper neque.</p><p class=\"ql-align-justify\">Donec tristique elit non diam ultrices, a elementum dui consequat. Vestibulum molestie libero nisl, a tristique nunc vehicula eget. Sed pharetra justo id nulla interdum dapibus. In hac habitasse platea dictumst. Vivamus cursus vitae urna a interdum. Morbi ut ligula felis. Etiam orci orci, congue sit amet risus ac, dictum lacinia tellus. Nam vel nisl sem. Curabitur semper ut nisl dictum malesuada. Donec sed laoreet purus. Nunc ac elit molestie, semper magna id, sollicitudin nunc. Donec tincidunt, turpis sit amet vulputate ornare, velit sem interdum urna, sed euismod quam dui non enim. Sed pellentesque viverra magna, vel interdum massa accumsan ut. Quisque venenatis massa tellus, non dictum justo euismod ut. Donec non ligula nulla. Integer feugiat ante id justo commodo ornare.</p><p><br></p>",
          news: {
              limit: null,
              order: "desc",
              collectionId: "ppbq9qdylv",
              sort: null,
          },
          subtitle: "A New Way of Thinking",
      },
      order: null,
      slug: "a-new-way-of-thinking",
      name: null,
      id: "fhsscofq7s",
      createdAt: 1658654472629,
      parentId: "ppbq9qdylv",
      deletedAt: null,
      templateId: "news-collection",
      updatedAt: 1658654472629,
  },
  {
      createdAt: 1658671299590,
      deletedAt: null,
      content: {
          body: "<p>Hello</p>",
          image: {
              focus: {
                  y: 0,
                  x: 0,
              },
              src: "uploads/d7f40f8abff59b95b28209f778a90720",
          },
          description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscip ex ea commodo consequat. Duis aut irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non.</p>",
          name: "Criminal Justice",
      },
      order: null,
      id: "bwkcj1l9ka",
      metadata: {},
      updatedAt: 1658671299590,
      slug: "issue--bwkcj1l9ka",
      parentId: "yyjpkpjujo",
      name: "Criminal Justice",
      templateId: "issues-collection",
  },
  {
      parentId: "e9uhubnabe",
      name: null,
      createdAt: 1658668726744,
      slug: "endorsement--a3xgielzvo",
      metadata: {},
      templateId: "endorsements-collection",
      deletedAt: null,
      order: null,
      content: {
          name: "Ruth Wu",
          type: [
              "team",
          ],
          title: "Software Engineer",
          image: {
              src: "uploads/caa995cad2ddaaa1ce2cc31071be10dd",
          },
      },
      updatedAt: 1658668726744,
      id: "a3xgielzvo",
  },
  {
      slug: "design--6u96gzzt64",
      deletedAt: null,
      name: null,
      id: "6u96gzzt64",
      order: null,
      parentId: null,
      templateId: "design-settings",
      content: {
          color: {
              hex: "#3781e2",
              cta: "#f4ac3d",
          },
          serifFont: {
              family: "Roboto Condensed",
          },
          sansSerifFont: {
              family: "Montserrat",
          },
          theme: [
              "faded_glory",
          ],
          logo: {
              focus: {
                  y: 0,
                  x: 0,
              },
              src: "uploads/4dd6758486f61bcf22ff48f202a62bf5",
          },
      },
      metadata: {},
      updatedAt: 1658493149022,
      createdAt: 1658493149022,
  },
  {
      name: null,
      createdAt: 1659594526485,
      order: null,
      updatedAt: 1659594526485,
      metadata: {},
      slug: "contributions--6fy8772b2x",
      deletedAt: null,
      id: "6fy8772b2x",
      templateId: "contributions-settings",
      parentId: null,
      content: {
          defaultAmounts: [
              "10",
              "25",
              "50",
              "100",
          ],
          default_contribution_link: {
              name: "Contribute",
              recordId: null,
              keywords: [],
              url: "/donate",
              title: null,
              description: null,
              favicon: null,
          },
      },
  },
  {
      slug: "volunteer",
      order: null,
      id: "663o525ymt",
      content: {
          description: "<p>Come join the Universe team and change the way progressives organize!</p>",
          title: "Volunteer with Universe",
          background_image: {
              src: "uploads/c9a97f7212053a4c74cc2b25efc93517",
          },
      },
      deletedAt: null,
      createdAt: 1659636806772,
      metadata: {
          title: "Volunteer with Universe",
      },
      name: "Volunteer",
      templateId: "volunteer-page",
      updatedAt: 1659636806772,
      parentId: null,
  },
  {
      templateId: "news-collection",
      parentId: "ppbq9qdylv",
      content: {
          body: "<h3 class=\"ql-align-justify\">A New Way of Thinking</h3><p class=\"ql-align-justify\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec mollis sodales eros. Integer a enim erat. Nam nec pharetra nulla. Maecenas vitae ipsum sed leo ultricies condimentum non eu tortor. In porta erat urna, eget pulvinar elit semper in. Morbi pretium euismod convallis. Ut id nisi et leo fermentum dignissim eget vel orci. Integer pharetra velit nec massa posuere rhoncus. Donec rhoncus molestie vehicula. Integer facilisis mi at rutrum suscipit. Pellentesque suscipit, mauris nec lobortis iaculis, elit erat congue nisl, vitae posuere velit odio id elit. Praesent dapibus porta magna in dictum. Maecenas eu interdum nisl. Mauris non tincidunt tellus. Morbi tincidunt sagittis ligula, non auctor purus. Morbi porta, eros vitae viverra tincidunt, lacus massa dignissim lorem, a pretium odio magna nec tortor.</p><p class=\"ql-align-justify\">Pellentesque nec arcu leo. Praesent finibus ante sit amet lectus posuere, vitae tristique felis sodales. Nullam tincidunt ipsum nec ipsum semper, sit amet gravida diam imperdiet. Fusce vel felis libero. Aenean ante metus, tincidunt nec ultrices eu, viverra non dolor. Suspendisse volutpat volutpat sodales. Maecenas et elit varius augue gravida elementum non vel eros. Morbi accumsan gravida massa, eu facilisis est fringilla non. Maecenas blandit urna in venenatis tincidunt. Aenean lobortis orci est, eu cursus urna sodales non. Duis elementum maximus eros, id tincidunt lectus. Fusce mattis nec felis ut molestie. Pellentesque sed eros nisl. Morbi laoreet luctus eros, a gravida diam ullamcorper vel. Sed ac volutpat magna, in consequat mi. Nullam eu lorem nec augue suscipit pulvinar.</p><p class=\"ql-align-justify\">Maecenas ut sem finibus magna molestie blandit ut eu diam. Maecenas faucibus nisl non velit tempor, sit amet dignissim dui ullamcorper. Pellentesque aliquam sollicitudin metus at congue. Morbi non dignissim lorem. Fusce eget dapibus magna, vel vulputate nunc. Suspendisse turpis risus, consequat ut lacinia et, finibus sit amet nulla. Integer vestibulum ut leo ut scelerisque. Proin nec interdum dui. Suspendisse suscipit sit amet metus at sodales. Duis justo nulla, tempor vitae convallis quis, euismod quis erat.</p><p class=\"ql-align-justify\">Sed et lorem cursus, ornare elit placerat, commodo tellus. Curabitur sed accumsan libero. Nullam semper gravida tellus quis convallis. Donec a pharetra justo, at vulputate neque. Integer et magna sit amet nulla blandit efficitur. Maecenas dapibus ligula velit, eu pellentesque augue tempus a. Praesent tempus finibus dui nec cursus. Sed diam quam, lobortis non ultrices sed, laoreet vitae massa. Duis quis tellus in enim luctus finibus a vel magna.</p><p class=\"ql-align-justify\">Sed consectetur erat non arcu accumsan, a dictum libero malesuada. Duis suscipit elit id mattis dapibus. Etiam augue neque, mattis eget nulla eu, eleifend scelerisque tellus. Suspendisse sollicitudin et ipsum in rhoncus. Quisque congue magna vel felis tincidunt, a maximus elit elementum. Mauris aliquet, ante quis viverra sodales, eros mi convallis urna, a cursus dolor massa aliquet libero. Nunc ut mi mauris.</p>",
          collection: [],
          header_image: {
              src: "uploads/27683a956e53b8d6293b384445a13eaf",
          },
          title: "Successful Campaign Launch",
          subtitle: "Thanks to you!",
      },
      id: "3t3hlc0fkz",
      deletedAt: null,
      createdAt: 1658654209181,
      order: null,
      metadata: {},
      updatedAt: 1658654209181,
      slug: "news--3t3hlc0fkz",
      name: null,
  },
  {
      slug: "seo--3gx2qx8bjg",
      updatedAt: 1659594590870,
      createdAt: 1659594590870,
      id: "3gx2qx8bjg",
      name: null,
      templateId: "seo-settings",
      order: null,
      deletedAt: null,
      metadata: {},
      content: {
          description: "Get your campaign online fast.",
          keywords: [
              "universe",
              "website",
              "campaign",
          ],
          title: "Universe Campaign Websites",
      },
      parentId: null,
  },
  {
      deletedAt: null,
      createdAt: 1659583274441,
      id: "3ei9a69juc",
      parentId: null,
      templateId: "petitions-page",
      slug: "petitions",
      content: {},
      order: null,
      metadata: {},
      updatedAt: 1659583274441,
      name: "Petitions",
  },
  {
      name: null,
      content: {
          instagram: "https://instagram.com",
          facebook: "https://facebook.com",
          email: "contact@universe.app",
          twitter: "https://twitter.com",
      },
      updatedAt: 1658668941369,
      deletedAt: null,
      slug: "social--2aboag44wk",
      parentId: null,
      id: "2aboag44wk",
      templateId: "social-settings",
      order: null,
      metadata: {},
      createdAt: 1658668941369,
  },
  {
      slug: "issue--27wgvc7p2c",
      content: {
          image: {
              focus: {
                  y: 0,
                  x: 0,
              },
              src: "uploads/cec5bdf27b5cbb1515300b30cc996394",
          },
          description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscip ex ea commodo consequat. Duis aut irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non.</p>",
          name: "Climate Change",
      },
      id: "27wgvc7p2c",
      deletedAt: null,
      createdAt: 1658671236574,
      order: null,
      updatedAt: 1658671236574,
      name: "Climate Change",
      metadata: {},
      templateId: "issues-collection",
      parentId: "yyjpkpjujo",
  },
  {
      order: null,
      deletedAt: null,
      content: {
          disclosures: "<p>PAID FOR BY UNIVERSE DIGITAL INC</p>",
      },
      createdAt: 1658667700526,
      updatedAt: 1658667700526,
      id: "1349347syk",
      parentId: null,
      name: null,
      metadata: {},
      templateId: "footer-settings",
      slug: "footer--1349347syk",
  },
  {
      templateId: "issues-collection",
      deletedAt: null,
      content: {
          image: {
              focus: {
                  y: 0,
                  x: 0,
              },
              src: "uploads/8bec27e564f3a691971b05f603a7bf9e",
          },
          name: "Education",
          description: "<p>Lorem ipsum dolor sit amet, consectetur adipiscip ex ea commodo consequat. Duis aut irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non.</p>",
      },
      updatedAt: 1658450994491,
      createdAt: 1658450994491,
      parentId: "yyjpkpjujo",
      metadata: {},
      order: null,
      name: "Education",
      slug: "issue--02dtw3k1i3",
      id: "02dtw3k1i3",
  },
];

export default DATA;
